### ISSUE TITLE
Multi tabs with the same title

### ISSUE THREAD

**Issue by aszmyd** [djungelorm/sphinx-tabs#12]
Is it possible to have multi tabs with the same title 
We're writting an REST API docs with those tabs and need to document different REST responses for the same response code.

   
    .. tabs::
    
        .. code-tab:: json 400

            {
                  "message": "Possible issue 1"
            }

        .. code-tab:: json 400
    
            {
                 "message": "Possible issue 2"
            }

Im aware i can name the tabs differently but it would be really useful if this plugin could handle such situation.

**Comment by djungelorm** [comment]
Code tabs are actually group tabs - and the name is used to work out the grouping, so having the same name was causing a clash. I've committed a change that allows this use case.

**Comment by djungelorm** [comment]
I wonder if we should add another type of tab, so that you can have non-group code tabs.

I.e. have directives `tab`, `group-tab`, `code-tab` and `group-code-tab`?

**Comment by aszmyd** [comment]
Thanks! Yeah maybe having non-group code tabs would help sometimes. In my case You'r current change should do the job i think. @djungelorm do You have a plan when it'll be released?

**Comment by djungelorm** [comment]
I've released v1.1.1 on pypi with this change
