### ISSUE TITLE
Using variables inside of code tabs

### ISSUE THREAD

**Issue by aszmyd** [djungelorm/sphinx-tabs#13]
Is it possible to use some kind of variable mechanism in tabs contents?

I.e. i have such line in `conf.py`:

    my_config_value = 42
    rst_epilog = '.. |my_conf_val| replace:: %d' % my_config_value

And when i use it in some regular text like so:

    My config value is |my_conf_val|!

Sphinx nicely replace the var and output as follows:

    My config value is 42!

But when i try the same using this tabs extension:

    .. tabs::

        .. code-tab:: javascript

            // |my_conf_val|

I get unreplaced `|my_conf_val|` string in the output.

Is it possible to achieve something similar (variables) with this extension?

**Comment by djungelorm** [comment]
This is an issue with sphinx, as the following also goes unreplaced:
```
.. code-block:: javascript

   // |my_conf_val|
```

A `code-tab` is just syntactic sugar for a `code-block` nested in a `tab`, so the issue here is that sphinx does not do this replacement in a `code-block`.

**Comment by aszmyd** [comment]
@djungelorm thanks for pointing that out! You're right of course, this is more low level issue. I've pushed an issue in [sphinx repo](https://github.com/sphinx-doc/sphinx/issues/4054)
