### ISSUE TITLE
WARNING: Not copying tabs assets! Not compatible with dirhtml builder

### ISSUE THREAD

**Issue by markuszoeller** [djungelorm/sphinx-tabs#14]
I tried to use the package in combination with the blog building packge `ablog`.
When building the code with `ablog build`, I get this warning:
```
WARNING: Not copying tabs assets! Not compatible with dirhtml builder
```

The following example content gets *not* rendered as tabs:
```
.. tabs::

   .. tab:: Apples

      Apples are green, or sometimes red.

   .. tab:: Pears

      Pears are green.

   .. tab:: Oranges

      Oranges are orange.
```

It gets rendered like this:
```
Apples
Pears
Oranges
Apples are green, or sometimes red.
Pears are green.
Oranges are orange.
```

I'd really love to use your package, it does exactly what I want with the interface I want.

**Comment by markuszoeller** [comment]
FWIW, here's the source of my blog where I wanted to integrate your sphinx extension: https://github.com/markuszoeller/markuszoeller.github.io
You can use the script `./build_sources.sh` to trigger the build.

**Comment by djungelorm** [comment]
I've added the dirhtml to the list of html builders, which should fix this issue.
An updated version should is on pypi now for you to use.

**Comment by markuszoeller** [comment]
That was fast! Works like a charm, thanks mate!
