### ISSUE TITLE
:name: not working in code-tab

### ISSUE THREAD

**Issue by PoslavskySV** [djungelorm/sphinx-tabs#16]
Tab names in code-tabs are not working. The following code

```
.. tabs::

   .. code-tab:: scala
      :name: Scala 1

   .. code-tab:: scala
      :name: Scala 2
```

gives 
<img width="216" alt="sssss" src="https://user-images.githubusercontent.com/3834261/31688046-bd516344-b393-11e7-8322-0f0e9d196b22.png">

though I expect "Scala 1" tab and "Scala 2" tab.

**Comment by djungelorm** [comment]
The syntax for this is actually:
```
.. tabs::

   .. code-tab:: scala Scala 1

   .. code-tab:: scala Scala 2
```

Not sure where you found this :name: syntax?!

**Comment by PoslavskySV** [comment]
ops, I was wrong:) Thanks for the clarification!
