### ISSUE TITLE
WARNING: Not copying tabs assets! Not compatible with readthedocsdirhtml builder

### ISSUE THREAD

**Issue by scanf** [djungelorm/sphinx-tabs#18]
Experiencing the titled issue on one read the docs page but not consistently. Snippet and links below. Has anyone else experienced this? Is there any workaround?

```
.. only:: html

   .. tabs::
     .. group-tab:: JSON

        .. literalinclude:: ../examples/policies/l3.json
     .. group-tab:: YAML

        .. literalinclude:: ../examples/policies/l3.yaml

.. only:: epub or latex

        .. literalinclude:: ../examples/policies/l3.json
```

- Works here http://scanfcilium.readthedocs.io/en/latest/policy.html#example-basic
- Warning here http://cilium.readthedocs.io/en/latest/policy/#example-basic

Thanks.

**Comment by djungelorm** [comment]
I've added readthedocsdirhtml to the list of valid builders, and also added a config option called sphinx_tabs_valid_builders to be able to add custom builders to the valid list in future.

v1.1.6 has been released which should fix this issue.

**Comment by scanf** [comment]
It works. Thanks a lot.
