### ISSUE TITLE
linkcheck warning: Not copying tabs assets! Not compatible with linkcheck builder

### ISSUE THREAD

**Issue by honzajavorek** [djungelorm/sphinx-tabs#26]
I want to lint external links in my docs in the CI, so I want the `linkcheck` builder to fail on warnings. I use

```
sphinx-build -nW -b linkcheck . _build/
```

But then I get a following failure:

```
Not copying tabs assets! Not compatible with linkcheck builder
```

Is there a way how to overcome this?

**Comment by honzajavorek** [comment]
To be clear, I'm willing to contribute a solution, I'm just not entirely sure what is the best way to tackle this.

**Comment by djungelorm** [comment]
There is a configuration option to allow additional builders to be considered compatible. Add the following to your conf.py:

```
sphinx_tabs_valid_builders = ['linkcheck']
```

**Comment by honzajavorek** [comment]
Oh, awesome! I was just about to use a hack alongside `sphinx_tabs_nowarn = 'linkcheck' in sys.argv`, but this is much better. Thank you, this works!

**Comment by honzajavorek** [comment]
By the way, this extension is absolute gold and I totally love it! Thank you for creating this!

**Comment by djungelorm** [comment]
Thanks!
