### ISSUE TITLE
Nested Tabs

### ISSUE THREAD

**Issue by jreed1701** [djungelorm/sphinx-tabs#29]
Great tool! Would be really nice if one could nest tabs within tabs. Is there any support for that on the horizon?

**Comment by djungelorm** [comment]
It wasn't planned, but I can certainly look into it.

**Comment by djungelorm** [comment]
This has been added in v1.1.9. You can see a demo here: https://djungelorm.github.io/sphinx-tabs/

**Comment by jreed1701** [comment]
This will be useful! Thank you! ;)
