### ISSUE TITLE
css/tabs.css and js/tabs.js are missing

### ISSUE THREAD

**Issue by dmed256** [djungelorm/sphinx-tabs#3]
Thanks for updating the pypi package to 0.2.0!
Hmm, I'm having issues with the _static files on readthedocs but not locally

```
http://occa.readthedocs.io/en/latest/_static/sphinx_tabs/tabs.css Failed to load resource: the server responded with a status of 404 (OK)
```

It looks like the right place, but I guess not :(
Any clues?

**Comment by djungelorm** [comment]
Works for me locally too.

I set up a test repo with readthedocs and get the same behaviour as you:
https://github.com/djungelorm/sphinx-tabs-rtd-test
http://sphinx-tabs-rtd-test.readthedocs.io/en/latest/

Will continue to investigate...

**Comment by djungelorm** [comment]
I have a potential fix, but rtd seems to be having some problems at the moment. I keep getting:
```Failed to import project: Failed to get code from 'https://github.com/djungelorm/sphinx-tabs-rtd-test.git' (git fetch): 128 Stderr: error: unable to create temporary file: No space left on device fatal: failed to write object fatal: unpack-objects failed``` for my builds!

The problem is that the extension check if the builder is "html" and silently disables itself if it's not. RTD using a builder called "readthedocs" for multi-page html builds.

**Comment by djungelorm** [comment]
fe9e2c49

Should be fixed in v0.2.1 which is now on pypi

**Comment by dmed256** [comment]
Sorry for the late reply, just got off work
Awesome detective skills, will update my rtd soon :D
Thanks again!

**Comment by dmed256** [comment]
Worked, thanks so much
Glad I started doing doc stuff 2 weeks at you started this project hehe
