### ISSUE TITLE
Group tabs are no longer synced as of 1.1.9

### ISSUE THREAD

**Issue by mattsb42-aws** [djungelorm/sphinx-tabs#31]
You can actually see this in the sample site[1].

In testing with one of my sites, the group synchronization worked in 1.1.8 but broke with 1.1.9.

Verified viewing in for Firefox and Chrome, just in case this was a browser issue.

[1] https://djungelorm.github.io/sphinx-tabs/

**Comment by djungelorm** [comment]
Should be fixed in 1.1.10. Thanks for reporting!
