### ISSUE TITLE
Tabs in Internet Explorer not working

### ISSUE THREAD

**Issue by jreed1701** [djungelorm/sphinx-tabs#33]
Hello Again!

Again,  I really appreciate having this nifty tool. Has helped me organize my work a whole lot easier.  

I was wondering, and this may or may not be an issue, I cannot get these tabs to work in internet explorer.  Clicking the tab does nothing.  Maybe it's a javascript issue? Firefox works fine. Don't know about chrome. Not using it.  Anyway, thought i'd let you know one developer to another.

**Comment by djungelorm** [comment]
Thanks for the info. I've only tested it with Firefox and Chome. It uses jquery to do what minimal javascript is required for the tabs to appear/disappear. I just assumed it would be cross-browser compatible, but I guess I was wrong... Will investigate.

**Comment by alberpilot** [comment]
Hello @djungelorm, any update on this? 
Thanks

**Comment by djungelorm** [comment]
Not yet, but I have been doing some updates to the plugin, including updating Semantic UI to the latest version, which is the JS library the plugin uses. Hopefully that fixes it, will test soon before I do a new release.

**Comment by djungelorm** [comment]
Looks like a simple bug where IE doesn't support one of the basic string functions in ES6... I'm working on a fix and should get it released soon.

**Comment by djungelorm** [comment]
Fixed in v1.1.12
