### ISSUE TITLE
Not copying tab assets - epub

### ISSUE THREAD

**Issue by Daltz333** [djungelorm/sphinx-tabs#45]
Epub generation throws a warning when on Sphinx 2.1.0

![image](https://user-images.githubusercontent.com/10674555/59472138-7f1e7e00-8e0b-11e9-85c8-8ba3cc7ec01f.png)

**Comment by djungelorm** [comment]
That's expected. sphinx-tabs only works with builders that generate HTML+JS+CSS for a web browser.

You can suppress the warning by setting `sphinx_tabs_nowarn = True` in your config.
