### ISSUE TITLE
Adding a link to a live example

### ISSUE THREAD

**Issue by Naereen** [djungelorm/sphinx-tabs#5]
Hi,

First, thanks and :clap: for this neat small Sphinx extension.
It's well done, easy to install and use, great! :1st_place_medal: !

If you want to add a link to a "live example", I wrote a small page demonstrating your extension for my (Sphinx powered) website: http://perso.crans.org/besson/test-tabs.en.html#details
![test tabs](https://user-images.githubusercontent.com/11994719/26920439-5688e9fa-4c39-11e7-94b2-f88023295cc0.png)

Regards

**Comment by Naereen** [comment]
@djungelorm any update?

**Comment by djungelorm** [comment]
Sorry been busy lately.

Your demo doesn't demonstrate anything more than the readme on here... so feeling reluctant to link to it... sorry

**Comment by Naereen** [comment]
Agreed, it's just that seeing a live webpage instead of gif can help. (to read the source code, for instance)

If you prefer to host the HTML pages produced from the source in `test` somewhere, that's enough
(there is probably not much do, if the HTML pages are in the `gh-pages` branch, https://djungelorm.github.io/sphinx-tabs/test/ will show them, if the repo is configured to use GitHub pages)

**Comment by djungelorm** [comment]
I've added the live demo here: https://djungelorm.github.io/sphinx-tabs/ and linked it from the README.
Thanks for the suggestion!

**Comment by Naereen** [comment]
OK!
