### ISSUE TITLE
Any way to customize the code-tab label/tab name

### ISSUE THREAD

**Issue by angela0xdata** [djungelorm/sphinx-tabs#52]
I show examples of how to run code using Python and R. But when I use

```
.. tabs::
   .. code-tab:: r

	library(somelibrary)
```

The label in the output is "S". I'm assuming this has something to do with the R/S lexers 
http://pygments.org/docs/lexers/#lexers-for-the-r-s-languages. 

<img width="738" alt="Screen Shot 2019-10-07 at 12 06 42 PM" src="https://user-images.githubusercontent.com/18428990/66340890-0b910700-e8fb-11e9-8a2b-6f49fe987509.png">

Is there any way to change the label?

I tried using `group-tab` with coded text, but the highlighting is a little different.

**Comment by stefanodavid** [comment]
This should work:

```
.. tabs::
   .. code-tab:: r R

	library(somelibrary)
```
The first r is the lexer, the second (and subsequent) the label.

**Comment by angela0xdata** [comment]
That worked, thanks!!!
