### ISSUE TITLE
Header name is 'S' for r language 

### ISSUE THREAD

**Issue by runawayhorse001** [djungelorm/sphinx-tabs#68]
The header name for r language is wrong, it shows 'S': 

![image](https://user-images.githubusercontent.com/8015506/84788976-5c421f00-afb5-11ea-8bde-f36e763f53e5.png)

**Comment by stefanodavid** [comment]
hi @runawayhorse001, I gave a workaround for exactly this issue in a comment to issue #52.

**Comment by runawayhorse001** [comment]
@stefanodavid Thank you so much!
