### ISSUE TITLE
Multi-word tab title raises exception during build 

### ISSUE THREAD

**Issue by bwohlberg** [djungelorm/sphinx-tabs#8]
If `.. tab::` is followed by more than a single word, as in this example

```
.. tabs::

   .. tab:: Red Apples

      Apples are green, or sometimes red.

   .. tab:: Pears

      Pears are green.
```

the sphinx build raises a `json.decoder.JSONDecodeError` exception. This bug does not seem to affect `.. group-tab::`.

**Comment by djungelorm** [comment]
Thanks for reporting!
